version: '3'

services:
  app:
    image: ambientum/php:7.4-nginx
    container_name: laravel_app
    volumes:
      - .:/var/www/app
    env_file:
      - .env
    ports:
      - "${DOCKER_HTTP_PORT}:8080"
      - "${DOCKER_HTTPS_PORT}:443"
    links:
      - db

  db:
    image: mariadb:10.1
    container_name: laravel_db
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - .env
    ports:
      - "${DOCKER_DB_PORT}:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_RANDOM_ROOT_PASSWORD: '1'

volumes:
  db:
